[package]
name = "pwned-rs"
version = "0.1.0"
authors = ["Tim Hütz <tim@huetz.biz>"]
edition = "2018"
description = "Tool for locally checking existing of passwords in the leak files provided by Troy Hunt."

[dependencies]
chrono = "*"
clap = {version = "*", features = ["yaml"]}
fern = "*"
log = "*"
rpassword = "*"
rust-crypto = "*"
